services:
    ketchupbot-discord:
        image: ghcr.io/smallketchup82/ketchupbot-discord:main   # Change this line
        container_name: ketchupbot-updater
        build: .
        restart: unless-stopped
        env_file:
            - path: .env
              required: false
        labels:
          - "com.centurylinklabs.watchtower.enable=true"