services:
  ketchupbot-updater:
    image: ghcr.io/galaxypedia-wiki/ketchupbot-updater:latest
    restart: unless-stopped
    command: --turrets -ss "0 0 * ? * * *"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ketchupbot-updater/Dockerfile
