services:
    ketchupbot-updater:
        image: ghcr.io/smallketchup82/ketchupbot-updater:main
        container_name: ketchupbot-updater
        build: .
        restart: unless-stopped
        env_file:
            - path: .env
              required: false
        labels:
          - "com.centurylinklabs.watchtower.enable=true"